### ISSUE TITLE
The links to the documentation are not working

### ISSUE THREAD

**Issue by rilisema** [grails/grails-database-migration#256]
The link http://grails-plugins.github.io/grails-database-migration/3.0.x/index.html ends up in a github page saying:

"404
There isn't a GitHub Pages site here.

If you're trying to publish one, read the full documentation to learn how to set up GitHub Pages for your repository, organization, or user account."

Same for the other documentation links

**Comment by abcfy2** [comment]
Yes. The correct link should be https://grails.github.io/grails-database-migration/latest/

**Comment by rilisema** [comment]
Yes! That looks good, please update README accordingly.
